iepy/webui/corpus/urls.py
from django.conf.urls import patterns, url
from corpus import views
from corpus import api

urlpatterns = patterns(
    '',

    # Next item to label
    url(r'^next_segment_to_label/(?P<relation_id>\d+)/',
        views.next_segment_to_label,
        name='next_segment_to_label'),
    url(r'^next_document_to_label/(?P<relation_id>\d+)/',
        views.next_document_to_label,
        name='next_document_to_label'),

    # Navigate labeled items
    url(r'^navigate_labeled_segments/(?P<relation_id>\d+)/(?P<segment_id>\d+)/(?P<direction>\w+)/judgeless',
        views.navigate_labeled_segments,
        kwargs={"judgeless": True},
        name='navigate_labeled_segments_judgeless'),
    url(r'^navigate_labeled_documents/(?P<relation_id>\d+)/(?P<document_id>\d+)/(?P<direction>\w+)/judgeless',
        views.navigate_labeled_documents,
        kwargs={"judgeless": True},
        name='navigate_labeled_documents_judgeless'),
    url(r'^navigate_labeled_segments/(?P<relation_id>\d+)/(?P<segment_id>\d+)/(?P<direction>\w+)/',
        views.navigate_labeled_segments,
        name='navigate_labeled_segments'),
    url(r'^navigate_labeled_documents/(?P<relation_id>\d+)/(?P<document_id>\d+)/(?P<direction>\w+)/',
        views.navigate_labeled_documents,
        name='navigate_labeled_documents'),

    # Labeling Forms & Views
    url(r'^label_evidence_for_segment/(?P<relation_id>\d+)/(?P<segment_id>\d+)/',
        views.LabelEvidenceOnSegmentView.as_view(),
        name='label_evidence_for_segment'),
    url(r'^label_evidence_for_document/(?P<relation_id>\d+)/(?P<document_id>\d+)/',
        views.LabelEvidenceOnDocumentView.as_view(),
        name='label_evidence_for_document'),

    # Human in the loop
    url(r'^human_in_the_loop/(?P<relation_id>\d+)/(?P<segment_id>\d+)/',
        views.HumanInTheLoopView.as_view(),
        name='human_in_the_loop_segment'),
    url(r'^human_in_the_loop/(?P<relation_id>\d+)/',
        views.human_in_the_loop,
        name='human_in_the_loop'),

    # Document navigation
    url(r'^navigate_documents/(?P<document_id>\d+)/(?P<direction>\w+)/',
        views.navigate_documents,
        name='navigate_documents'),
    url(r'^navigate_document/(?P<document_id>\d+)/',
        views.DocumentNavigation.as_view(),
        name='navigate_document'),

    # CRUD Angular EOs
    url(r'^crud/entity_occurrence/?$', api.EOCRUDView.as_view(), name='eo_crud_view'),
    url(r'^crud/entity/?$', api.EntityCRUDView.as_view(), name='entity_crud_view'),

    url(r'^create_eo/?$', views.create_entity_occurrence, name='create_entity_occurrence'),
)

iepy/webui/webui/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Home page
    url(r'^$', "corpus.views.home", name='home'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^corpus/', include('corpus.urls', namespace='corpus')),
)

iepy/webui/corpus/models.py
from iepy.data.models import *
from . import signals

iepy/webui/corpus/forms.py
# -*- coding: utf-8 -*-
from django import forms

from corpus.models import EvidenceLabel

DEFAULT_LABEL = EvidenceLabel._meta.get_field('label').default


class EvidenceForm(forms.ModelForm):
    class Meta:
        model = EvidenceLabel
        fields = ["label"]
        widgets = {
            'label': forms.RadioSelect
        }

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance', None)
        restore_None = False
        if instance and instance.label is None:
            # When created, EvidenceLabel get None as label.
            # For such cases, on forms, we'll suggest the model.default
            instance.label = DEFAULT_LABEL
            restore_None = True
        super().__init__(*args, **kwargs)
        if restore_None:
            self.instance.label = None
        self.fields['label'].label = ''

    def has_changed(self, *args, **kwargs):
        changed = super().has_changed(*args, **kwargs)
        if not changed and self.instance.label == DEFAULT_LABEL:
            # On init we "hacked" the instance so the form was created showing our
            # desired default value. Because of that, we may not be seeing that change.
            if EvidenceLabel.objects.get(pk=self.instance.pk).label is None:
                changed = True
        return changed


class EvidenceOnDocumentForm(EvidenceForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        f_lbl = self.fields['label']
        f_lbl.widget = forms.HiddenInput()
        # "forms" is the name of some Angular context object on the frontend.
        f_lbl.widget.attrs['ng-value'] = 'forms["%s"]' % self.prefix
        f_lbl.required = False


class EvidenceToolboxForm(EvidenceForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        f_lbl = self.fields['label']
        prev_widget = f_lbl
        f_lbl.widget = forms.RadioSelect(choices=prev_widget.choices)
        f_lbl.widget.attrs['ng-model'] = 'current_tool'

iepy/webui/corpus/views.py
import json
from collections import defaultdict

from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.utils.decorators import method_decorator
from django.utils import formats
from django.views.generic.base import TemplateView
from django.http import HttpResponse, HttpResponseBadRequest

from extra_views import ModelFormSetView

from corpus.forms import EvidenceForm, EvidenceOnDocumentForm, EvidenceToolboxForm
from corpus.models import (
    Relation, TextSegment, IEDocument,
    EvidenceLabel, SegmentToTag, EntityKind
)

from iepy.data.db import EntityOccurrenceManager


def _judge(request):
    return request.user.username


class Home(TemplateView):
    template_name = 'corpus/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["relations"] = Relation.objects.all()

        segments_to_tag = SegmentToTag.objects.filter(done=False)
        relation_ids_to_tag = list(set(segments_to_tag.values_list("relation", flat=True)))
        relations_to_tag = Relation.objects.filter(id__in=relation_ids_to_tag)
        context["iepy_runs"] = relations_to_tag

        return context
home = login_required(Home.as_view())


def next_segment_to_label(request, relation_id):
    relation = get_object_or_404(Relation, pk=relation_id)
    segment = relation.get_next_segment_to_label(_judge(request))
    if segment is None:
        return render_to_response('message.html',
                                  {'msg': 'There are no more evidence to label'})
    return redirect('corpus:label_evidence_for_segment', relation.pk, segment.pk)


def next_document_to_label(request, relation_id):
    relation = get_object_or_404(Relation, pk=relation_id)
    doc = relation.get_next_document_to_label(_judge(request))
    if doc is None:
        return render_to_response('message.html',
                                  {'msg': 'There are no more evidence to label'})
    return redirect('corpus:label_evidence_for_document', relation.pk, doc.pk)


def _navigate_labeled_items(request, relation_id, current_id, direction, type_, judgeless):
    # The parameter current_id indicates where the user is situated when asking
    # to move back or forth
    type_name = 'document' if type_ == IEDocument else 'segment'
    url_name = 'corpus:label_evidence_for_%s' % type_name
    relation = get_object_or_404(Relation, pk=relation_id)
    current = get_object_or_404(type_, pk=current_id)
    current_id = int(current_id)
    going_back = direction.lower() == 'back'
    judge = _judge(request) if not judgeless else None

    obj_id_to_show = relation.labeled_neighbor(current, judge, going_back)
    if obj_id_to_show is None:
        # Internal logic couldn't decide what other obj to show. Better to
        # forward to the one already shown
        response = redirect(url_name, relation.pk, current_id)
        messages.add_message(request, messages.WARNING,
                             'No other %s to show.' % type_name)
        return response
    else:
        response = redirect(url_name, relation.pk, obj_id_to_show)
        if obj_id_to_show == current_id:
            direction_str = "previous" if going_back else "next"
            messages.add_message(
                request, messages.WARNING,
                'No {0} {1} to show.'.format(direction_str, type_name))
        return response


def navigate_labeled_segments(request, relation_id, segment_id, direction, judgeless=False):
    return _navigate_labeled_items(
        request, relation_id, segment_id, direction, TextSegment, judgeless
    )


def navigate_labeled_documents(request, relation_id, document_id, direction, judgeless=False):
    return _navigate_labeled_items(
        request, relation_id, document_id, direction, IEDocument, judgeless
    )


class _BaseLabelEvidenceView(ModelFormSetView):
    form_class = EvidenceForm
    model = EvidenceLabel
    extra = 0
    max_num = None
    can_order = False
    can_delete = False

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    @property
    def judge(self):
        return _judge(self.request)


class LabelEvidenceOnSegmentBase(_BaseLabelEvidenceView):
    template_name = 'corpus/segment_questions.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.segment.hydrate()
        title = "Labeling Evidence for Relation {0}".format(self.relation)
        subtitle = 'For Document "{0}", Text Segment id {1}'.format(
            self.segment.document.human_identifier,
            self.segment.id)

        context.update({
            'title': title,
            'subtitle': subtitle,
            'segment': self.segment,
            'segment_rich_tokens': list(self.segment.get_enriched_tokens()),
            'relation': self.relation,
            'draw_navigation': True,
        })
        return context

    def get_segment_and_relation(self):
        if hasattr(self, 'segment') and hasattr(self, 'relation'):
            return self.segment, self.relation
        self.segment = get_object_or_404(TextSegment, pk=self.kwargs['segment_id'])
        self.segment.hydrate()
        self.relation = get_object_or_404(Relation, pk=self.kwargs['relation_id'])
        evidences = list(self.segment.get_evidences_for_relation(self.relation))
        for ev in evidences:
            ev.get_or_create_label_for_judge(self.relation, self.judge)  # creating EvidenceLabels
        return self.segment, self.relation

    def get_queryset(self):
        segment, relation = self.get_segment_and_relation()
        return super().get_queryset().filter(
            judge=self.judge, evidence_candidate__segment=self.segment,
            relation=self.relation,
            labeled_by_machine=False,
        )

    def get_success_url(self):
        return reverse('corpus:next_segment_to_label', args=[self.relation.pk])

    def formset_valid(self, formset):
        """
        Add message to the user, and set who made this labeling (judge).
        """
        for form in formset:
            if form.has_changed():
                form.instance.judge = str(self.request.user)
        result = super().formset_valid(formset)
        messages.add_message(self.request, messages.INFO,
                             'Changes saved for segment {0}.'.format(self.segment.id))
        return result


class LabelEvidenceOnSegmentView(LabelEvidenceOnSegmentBase):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        for formset in context["formset"]:
            instance = formset.instance
            evidence = instance.evidence_candidate
            instance.all_labels = evidence.labels.all()

        context["draw_navigation"] = True
        context["draw_postags"] = True

        return context


def human_in_the_loop(request, relation_id):
    relation = get_object_or_404(Relation, pk=relation_id)

    segments_to_tag = SegmentToTag.objects.filter(
        relation=relation,
        done=False,
    ).order_by("-modification_date")

    if not segments_to_tag:
        return render_to_response(
            'message.html',
            {'msg': 'There are no more evidence to label'}
        )

    segment_to_tag = segments_to_tag[0]
    return redirect(
        'corpus:human_in_the_loop_segment',
        relation.pk, segment_to_tag.segment.pk
    )


class HumanInTheLoopView(LabelEvidenceOnSegmentBase):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["draw_navigation"] = False
        return context

    def get_success_url(self):
        return reverse('corpus:human_in_the_loop', args=[self.relation.pk])

    def formset_valid(self, formset):
        result = super().formset_valid(formset)

        segment = get_object_or_404(TextSegment, pk=self.kwargs["segment_id"])
        segment_to_tag = SegmentToTag.objects.get(
            segment=segment,
            relation=self.relation,
        )
        segment_to_tag.done = True
        segment_to_tag.save()
        return result


class LabelEvidenceOnDocumentView(_BaseLabelEvidenceView):
    template_name = 'corpus/document_questions.html'
    form_class = EvidenceOnDocumentForm

    def get_text_segments(self, only_with_evidences=False):
        if only_with_evidences:
            return self.relation._matching_text_segments().filter(
                document_id=self.document.id).order_by('offset').distinct()
        else:
            return self.document.get_text_segments()

    def get_context_data(self, **kwargs):
        ctx = super(LabelEvidenceOnDocumentView, self).get_context_data(**kwargs)
        title = "Labeling Evidence for Relation {0}".format(self.relation)
        subtitle = 'For Document "{0}"'.format(self.document.human_identifier)

        segments_with_rich_tokens = []
        for segment in self.get_text_segments(only_with_evidences=True):
            segment.hydrate()
            segments_with_rich_tokens.append(
                {'id': segment.id,
                 'rich_tokens': list(segment.get_enriched_tokens())}
            )

        if self.document.syntactic_sentences:
            parsed_sentences = [x.pprint() for x in self.document.syntactic_sentences]
        else:
            parsed_sentences = [""] * len(segments_with_rich_tokens)

        if not segments_with_rich_tokens:
            ctx = {
                'title': title,
                'document': self.document,
                'relation': self.relation,
                'eos_propperties': {},
                'relations_list': [],
                'forms_values': [],

iepy/webui/corpus/templates/corpus/base.html
{% extends "admin/base_site.html" %}
{% load static %}

{% block extrahead %}
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}" />
    <link rel="stylesheet" href="{% static 'css/foundation-icons.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/iepy.css' %}" />

    <!-- Javascript -->
    <script src="{% static 'js/vendor/modernizr.js' %}"></script>
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/foundation.min.js' %}"></script>
    <script src="{% static 'js/foundation/foundation.dropdown.js' %}"></script>
    <script src="{% static 'js/foundation/foundation.reveal.js' %}"></script>
    <script>
        $(document).foundation();
    </script>
    {% block extra_js %}{% endblock %}
{% endblock %}

{% block branding %}
    <h1 id="site-name">IEPY administration</h1>
{% endblock %}

{% block title %}
    {{ title }} {% if title %} | {% endif %} IEPY
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="/">Home</a>
        {% if title %} &rsaquo; {{ title }}{% endif %}

        <div class="label-mode-switch">
            {% block label_mode_switch %}{% endblock %}
        </div>
    </div>
    {% if draw_navigation %}
        <div class="navigation large-12 columns">
            {% block navigation %} {% endblock %}
        </div>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="large-12 columns">
            {% block inner_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

iepy/webui/corpus/templates/corpus/document.html
{% extends "corpus/base.html" %}
{% load static %}
{% load iepy_tags %}

{% block content_title %}{% endblock %}
{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/segment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/document.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/segment_questions.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/document_questions.css' %}" />
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/vendor/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/angular.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/angular-route.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/angular-resource.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/angular-cookies.min.js' %}"></script>

    <script type="text/javascript">
        var eo_creation_url = "{% url 'corpus:create_entity_occurrence' %}";
    </script>
    <script type="text/javascript" src="{% static 'js/document_questions.js' %}"></script>
{% endblock %}

{% block navigation %} 
    <a href="{% url 'corpus:navigate_documents' document.pk 'back' %}">
        &lsaquo; Previous document
    </a>|
    <a href="{% url 'corpus:navigate_documents' document.pk 'forth' %}">
        Next document &rsaquo;
    </a>
{% endblock %}

{% block inner_content %}
    <div class="wrapper" ng-app="labelingApp" ng-controller="QuestionsController">
        <div class="row">
            <div class="large-2 columns">
                <label>Display metadata</label>
                <input type="radio" name="metadata_visible" value="pos" ng-model="metadata_visible" id="postag-option">
                <label for="postag-option">POS tag</label> <br />
                <input type="radio" name="metadata_visible" value="lemma" ng-model="metadata_visible" id="lemma-option">
                <label for="lemma-option">Lemma</label> <br />
                <input type="radio" name="metadata_visible" value="none" ng-model="metadata_visible" id="none-option">
                <label for="none-option">None</label> <br />
            </div>
            <div class="large-10 columns document" data-document-id="{{ document.id }}">
                {% include "corpus/segments_render.html" %}
            </div>
        </div>
    </div>

    {% include "corpus/eo_edition_modal.html" %}
    {% include "corpus/eo_creation_modal.html" %}
{% endblock %}

iepy/webui/corpus/templates/corpus/document_questions.html
{% extends "corpus/base.html" %}
{% load static %}
{% load iepy_tags %}

{% block content_title %}{% endblock %}
{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/segment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/segment_questions.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/document_questions.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/csshake.min.css' %}" />
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/vendor/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/angular.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/angular-route.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/angular-resource.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/angular-cookies.min.js' %}"></script>

    <script type="text/javascript">
        var eos = {{ eos_propperties|safe }};
        var relations = {{ relations_list|safe }};
        var forms = {{ forms_values|safe }};
        var question_options = {{ question_options|safe }};
        var other_judges_labels = {{ other_judges_labels|safe }};
        var initial_tool = "{{ initial_tool }}";
        var eo_creation_url = "{% url 'corpus:create_entity_occurrence' %}";
        var different_kind = {%  if different_kind %} true {% else %} false {% endif %};
    </script>
    <script type="text/javascript" src="{% static 'js/document_questions.js' %}"></script>
{% endblock %}

{% block label_mode_switch %}
    <a href="{% url 'corpus:next_segment_to_label' relation.pk %}"
       title="Next segment with un-labeled evidences.">Label by segments</a>
{% endblock %}

{% block navigation %} 
    <div class="right">
        <a href="{% url 'corpus:navigate_labeled_documents_judgeless' relation.pk document.pk 'back' %}"
           title="Previous labeled document">Previous document labeled</a>
        &rsaquo;
        <a href="{% url 'corpus:navigate_labeled_documents_judgeless' relation.pk document.pk 'forth' %}"
           title="Next labeled document">Next document labeled</a>
    </div>

    <a href="{% url 'corpus:navigate_labeled_documents' relation.pk document.pk 'back' %}"
        title="Previous labeled document">Last document labeled by you</a>
    &rsaquo;
    <a href="{% url 'corpus:navigate_labeled_documents' relation.pk document.pk 'forth' %}"
       title="Next labeled document">Next document you labeled</a>
    &raquo;
    <a href="{% url 'corpus:next_document_to_label' relation.pk %}"
       title="Next document with un-labeled evidences.">Next document to label</a>
{% endblock %}

{% block inner_content %}
    <div class="wrapper" ng-app="labelingApp" ng-controller="QuestionsController">
        <div class="row">
            <div class="large-12 columns document" data-document-id="{{ document.id }}">
                {% if not segments %}
                    <br />
                    <div data-alert class="alert-box info radius">
                        There are no more things to tag in this document, try skipping to the next one!
                    </div>
                {% endif %}
            </div>
        </div>
        <br />
        <div class="row">
            <div class="large-3 medium-3 columns">
                <label>Display metadata</label>
                <input type="radio" name="metadata_visible" value="pos" ng-model="metadata_visible" id="postag-option">
                <label for="postag-option">POS tag</label>

                <input type="radio" name="metadata_visible" value="lemma" ng-model="metadata_visible" id="lemma-option">
                <label for="lemma-option">Lemma</label>

                <input type="radio" name="metadata_visible" value="none" ng-model="metadata_visible" id="none-option">
                <label for="none-option">None</label>
                <hr />

                {% if form_toolbox %}
                    <div class="toolbox">
                        Tag using this answer:
                        {{ form_toolbox }}

                        <span class="secondary label">
                            Use the number keys to switch between options
                        </span>
                    </div>
                {% endif %}
                {% if formset %}
                    <br />
                    For the rest of the posible relations the answer will be:
                    <form action="." method="POST">
                        {% csrf_token %}
                        {{ formset.management_form }}
                        <input type="hidden" id="partial-save" name="partial_save" value="" />

                        <div class="row">
                            <div class="large-12 columns non-selected-relations">
                                {{form_for_others}}
                            </div>
                        </div>

                        {% for form in formset %}
                            {{ form.as_p }}
                        {% endfor %}

                        <div class="row">
                            <div class="large-6 columns">
                                <input class="button" type="submit" value="Save and continue" />
                            </div>
                        </div>
                    </form>
                {% endif %}

                {% if segments %}
                    <div class="prev-relations-wrapper">
                        View labels by:
                        <select class="judge-answers-wrapper">
                            <option value="me">
                                Me
                            </option>
                            {% for judge in other_judges %}
                                <option value="{{ judge }}">
                                    {{ judge }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                {% endif %}
            </div>


            <div class="large-9 medium-9 columns">
                {% if subtitle %} <div class="title"> {{subtitle}} </div> {% endif %}
                <svg xmlns="http://www.w3.org/2000/svg">
                    <defs>
                        {% for i in question_options %}
                            <marker id="arrow-point-{{ i }}" markerWidth="13" markerHeight="13" refx="2" refy="6" orient="auto">
                                <path d="M2,1 L2,10 L10,6 L2,2" class="arrow-point-{{ i }}"/>
                            </marker>
                        {% endfor %}
                    </defs>
                </svg>

                <div class="segments">
                <br />
                    {% include "corpus/segments_render.html" %}
                </div>
            </div>
        </div>
    </div>

    {% include "corpus/eo_edition_modal.html" %}
    {% include "corpus/eo_creation_modal.html" %}
{% endblock %}

iepy/webui/corpus/templates/corpus/entity_occurrence_modal.html
<div id="eoModal" class="reveal-modal large" data-reveal>
    <h2>Manage Entity Occurrence</h2>
    <div class="entity_id">Entity id: <span></span></div>
    <div class="entity_kind">Entity kind: <span></span></div>
    <div class="message"></div>
    <div class="delete">
        <a class="remove-eo-ask">Delete</a>
        <div class="remove-confirm-wrapper">
            Are you sure to delete the occurrence? 
            <small> This will have an impact on the possible relations </small>
            <br />
            <div class="remove-buttons">
                <a class="remove-eo-cancel">Cancel</a>
                <a class="remove-eo-confirm">Yes, i'm sure</a>
                <a class="remove-eo-confirm-all">Yes, also remove the entity and other occurrences</a>
            </div>
        </div>
    </div>
    <br />
    <div class="offsets">
        <p>Move occurrence limits:</p>
        <div class="segment">
        </div>
    </div>
    <a class="close-reveal-modal">&#215;</a>
    <div class="controls">
        <a class="button alert cancel">Cancel</a>
        <a class="button save">Save</a>
    </div>
</div>

iepy/webui/corpus/templates/corpus/segment_questions.html
{% extends "corpus/base.html" %}
{% load static %}

{% block content_title %}{{subtitle}}{% endblock %}
{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/segment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/segment_questions.css' %}" />
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/segment_questions.js' %}"></script>
{% endblock %}

{% block label_mode_switch %}
    <a href="{% url 'corpus:next_document_to_label' relation.pk %}"
       title="Next document with un-labeled evidences.">Label by documents</a>
{% endblock %}

{% block navigation %}
    <div class="right">
        <a href="{% url 'corpus:navigate_labeled_segments_judgeless' relation.pk segment.pk 'back' %}"
           title="Previous labeled document">Previous segment labeled</a>
        &rsaquo;
        <a href="{% url 'corpus:navigate_labeled_segments_judgeless' relation.pk segment.pk 'forth' %}"
           title="Next labeled document">Next segment labeled</a>
    </div>

    <a href="{% url 'corpus:navigate_labeled_segments' relation.pk segment.pk 'back' %}"
       title="Previous labeled segment">Last segment labeled by you</a>
    &rsaquo;
    <a href="{% url 'corpus:navigate_labeled_segments' relation.pk segment.pk 'forth' %}"
       title="Next labeled segment">Next segment you labeled</a>
    &raquo;
    <a href="{% url 'corpus:next_segment_to_label' relation.pk %}"
       title="Next segment with un-labeled evidences.">Next segment to label</a>
{% endblock %}


{% block inner_content %}
    <br />
    {% include "corpus/segment_render.html" %}
    <br /> <br />
    <div class="title"> Complete: </div>
    <form action="." method="POST">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for question_form in formset %}
            {% with obj=question_form.instance %}
            <div class="question row">
                <div class="large-4 columns">
                    {% with left_eo=obj.evidence_candidate.left_entity_occurrence %}
                    <span class="entity-occurrence"
                          data-occurrence-id="{{ left_eo.id }}"> {{ left_eo.alias }}
                    </span>
                    {% endwith %}
                    {{ relation.name }}

                    {% with right_eo=obj.evidence_candidate.right_entity_occurrence %}
                    <span class="entity-occurrence"
                          data-occurrence-id="{{ right_eo.id }}"> {{ right_eo.alias }}
                    </span>
                    {% endwith %}
                    ?
                </div>
                <div class="large-4 columns question-form-wrapper">
                    {{ question_form }}
                </div>
                <div class="large-4 columns">
                    <div class="previous-judgements">
                        {% for label in obj.all_labels %}
                            {% if label.label %}
                                <div class="previous-judgement">
                                    Labeled as <span class="value">{{label.label}}</span>
                                    by <span class="judge">{{label.judge|default:"unknown"}}</span>
                                    on <span class="date">{{labelobj.modification_date}}</span>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endwith %}
        {% endfor %}

        <div class="row">
            <div class="large-4 large-offset-4 columns">
                <input type="submit" value="save & see next" />
            </div>
        </div>
    </form>

{% endblock %}